### ISSUE TITLE
conflict with bart v4.03

### ISSUE THREAD

**Issue by curtcorum** [mrirecon/ox-bart#1]
I know this was not tested with bart 4.0.3 but:

https://github.com/mrirecon/bart/issues/132

I'll also be seeing if it will work with ochestra-sdk-1.7-1.

Curt

**Comment by jtamir** [comment]
with the exception of this, ox-bart should work with the latest bart. I have not yet tested orchestra 1.7. Let me know if you run into issues!

**Comment by jtamir** [comment]
Still have not checked the "noreturn" fix, but I updated support for Ox 1.7 (commit # a748c95)
